### ISSUE TITLE
How can I add new brush to plugin in a simplest way

### ISSUE THREAD

**Issue by DawidSadlik** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#1]
Hi
How can I add new brush to plugin in a simplest way? I do not want to contribute to the project (for now), but I want to add new brush quckly
Thanks

**Comment by crazy-max** [comment]
Hi,

Today all brushes are bundled. What brush do you want to add ?
There are several steps with npm and gulp to generate a syntaxhighlighter bundle.
I can add these steps in the README.md if you want.

**Comment by DawidSadlik** [comment]
I want to add brush for Structural Text http://infosys.beckhoff.com/content/1033/tc3_plc_intro/9007199390807179.html?id=21147207659243520115

**Comment by crazy-max** [comment]
All brushes used in the dokuwiki-plugin-syntaxhighlighter4 plugin are available on the [brushes page of the official SyntaxHighlighter repository](https://github.com/syntaxhighlighter/syntaxhighlighter/wiki/Brushes-and-Themes).
I you want to add a new brush that is not available on this page, consider [create a new issue on the Syntaxhighlighter repository](https://github.com/syntaxhighlighter/syntaxhighlighter).

**Comment by DawidSadlik** [comment]
Ok, I will try this way. Thanks
