### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by Danish22** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#10]
Hi,
While using the demo code for syntaxhighlighter provided in readme page on Playground , When I click preview received the below error - 
**Forbidden
You don't have permission to access /doku.php on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.**

> PS:I already changed the permission to 0755 for all the files.

What should I do now?

**Comment by crazy-max** [comment]
Hi,

Do you get the `404 Not Found` error when the plugin is disabled ?

**Comment by Danish22** [comment]
Hi, Am extremely sorry for reply late
After disabling the plugin and using the demo content of plugin I received the following error - 
****
Forbidden

You don't have permission to access /doku.php on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by crazy-max** [comment]
Hi,

If you disabled the plugin and still get this error it's not linked to the plugin but maybe another one.
