### ISSUE TITLE
Not compatible with vector template

### ISSUE THREAD

**Issue by blagodatov** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#11]
The plugin seems to be incompatible with the vector template.
Example page:
http://docs.loginet.ru/api:auth.svc:login
Plugin installed OK, highlighing not displayed(

**Comment by crazy-max** [comment]
Hi,

The plugin works well for me on the [vector template](https://www.dokuwiki.org/template:vector) on [DokuWiki Elenor of Tsort](https://www.dokuwiki.org/releasenames).
I suggest you disable plugins one by one to detect incompatibility.
Keep me in touch.

**Comment by crazy-max** [comment]
@blagodatov Any feedback ?
