### ISSUE TITLE
Uncaught Error: Brush wasn't configured for html-script option: bash

### ISSUE THREAD

**Issue by gpant** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#12]
I have tried a couple of brushes I wanted to use like bash and cpp and I always get the following error:
Uncaught Error: Brush wasn't configured for html-script option: bash
    at new HtmlScript (syntaxhighlighter.js:3414)
    at Object.highlight (syntaxhighlighter.js:217)
    at syntaxhighlighter.js:101
    at HTMLDocument.listener (syntaxhighlighter.js:5296)

Other brushes like php for example render fine without an issue.

**Comment by crazy-max** [comment]
I will investigate on your issue

**Comment by crazy-max** [comment]
Do you experience this issue with the latest release?

**Comment by gpant** [comment]
The last commit I see is from 2017/07/26 and I have already applied it with no changes in the issue unfortunately.

**Comment by crazy-max** [comment]
@gpant Can you paste your page with code here plz ?

**Comment by gpant** [comment]
On purpose I set one of them to bash so that you can see the error:
`https://eservices-greece.com/wiki/software/nginx`

**Comment by crazy-max** [comment]
I don't have any issue with your page on my local dokuwiki :

```
====== SyntaxHighlighter4 ======

===== sxh bash =====
<sxh bash>
cd ~
mkdir buildnginx
cd ~/buildnginx
useradd nginx
</sxh>
```

![image](https://user-images.githubusercontent.com/1951866/30089343-6894e392-92ac-11e7-9e7e-840999dd8b20.png)

Maybe it's your template or another plugin. Can you give me a list of your plugins and theme ?

**Comment by gpant** [comment]
I disabled every plugin and reverted to the default theme but the issue remains unfortunately. I will try to debug it a bit more and notify you.

Thanks for your help.

**Comment by crazy-max** [comment]
@gpant Any news about this ?

**Comment by gpant** [comment]
I am really sorry for the late reply, unfortunately I haven't had the time to debut this yet due to work, you can close the issue and I will open when I got some more information on it.
Thanks for your help.

**Comment by crazy-max** [comment]
Ok thanks

**Comment by teamunitedba-dev** [comment]
JFYI, It seems that there is an issue with the **plugin»syntaxhighlighter4»htmlScript** option.
Disabling it fix the brush render.

Regards!!

---

- DokuWiki version: Release 2018-04-22a "Greebo"
-  PHP version 5.6.24
- bootstrap3 template version: v2018-02-16

**Comment by gpant** [comment]
You are absolutely correct, I just disabled the option and the bash styling worked perfectly.
