### ISSUE TITLE
 add ODT support to syntaxhighlighter

### ISSUE THREAD

**Issue by rafaelaznar** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#13]
Could you add ODT support to syntaxhighlighter? Now code dissaperars from odt when you export the page. See https://www.dokuwiki.org/plugin:odt:rendersupport#odt_initiative

**Comment by crazy-max** [comment]
Hi,

Unfortunately support for this plugin will not be possible as it works on the client side using java-script. Only server-side plugins can support ODT export.

But you can use this website and copy paste to your ODT file : http://markup.su/highlighter/
