### ISSUE TITLE
Unwanted vertical scrollbar appearing

### ISSUE THREAD

**Issue by TheKojukinator** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#14]
Please see https://rtfm.kojukination.com/start for an example of this.

I've spent some time in the inspector trying to figure out what's going on, and the short of it is the container div seems to be just one pixel short of not needing the scrollbar. For example, if you go to my example page and inspect it, you'll probably see the container div like so...

`<div class="syntaxhighlighter  powershell" >`

The inspector tells me that its height is 240px, and I see the scrollbar. If I use the inspector to change the code to...

`<div class="syntaxhighlighter  powershell" style="height:241px">`

...the scrollbar will go away.

Unfortunately my CSS-foo is not strong enough to dissect all the existing style-sheet settings and figure out what is contributing to this extra pixel that doesn't fit. But I hope you can figure it out.

Otherwise I love your plugin and look forward to making use if it in my wiki. I'm just really OCD about that scrollbar :(

Thanks!

**Comment by crazy-max** [comment]
Hi,

No scrollbar for me on Firefox 54.0.1 :

![image](https://user-images.githubusercontent.com/1951866/28627455-289f33e6-7222-11e7-97d9-7642d66c03da.png)

What is your browser ?

**Comment by TheKojukinator** [comment]
I've confirmed no scrollbar in Edge and Firefox, however I do see it in IE and latest Chrome.

**Comment by crazy-max** [comment]
Ok i will investigate on that, thanks.

**Comment by TheKojukinator** [comment]
Awesome, thanks for the quick response.

**Comment by crazy-max** [comment]
@TheKojukinator Chrome 60.0.3112.78 ?

**Comment by TheKojukinator** [comment]
I was in `Version 59.0.3071.115 (Official Build) (32-bit)` but I just updated to `Version 60.0.3112.78 (Official Build) (32-bit)` and behavior is still the same. I also made sure to try it in incognito without any extensions.

**Comment by crazy-max** [comment]
Thanks I was able to reproduce your issue.

**Comment by crazy-max** [comment]
Must be ok with the latest release

**Comment by TheKojukinator** [comment]
Performed re-install via Extension Manager, and issue is gone. Thanks for fixing it so quick!

**Comment by crazy-max** [comment]
@TheKojukinator You're lucky i was on Github at this moment 😄
