### ISSUE TITLE
span tags appear in sxh block of page when searching dokuwiki for string

### ISSUE THREAD

**Issue by mbm329** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#15]
If I have a block on a page:
`<sxh>
testing123
</sxh>
`
When searching dokuwiki for "testing123", the page will appear in the search results.  Upon clicking the link from the search results to the page, the following in the sxh block of the rendered page:
`<span class="search_hit">testing123</span>`

Dokuwiki is effectively attempting to highlight the string that it found in the sxh code block.  However, instead of rendering the HTML code, it is just printing it to the screen.

**Comment by crazy-max** [comment]
Hi @mbm329,

Thanks for your report, i keep you in touch!

**Comment by crazy-max** [comment]
Here I am again @mbm329, I met this problem recently. I'm going to try to see if it's possible to fix this bug but in my opinion it will be necessary to overload the result of the rendering of the search what doesn't look easy.

**Comment by crazy-max** [comment]
Apparently, this is a known issue on dokuwiki. See splitbrain/dokuwiki#992.
