### ISSUE TITLE
Override <file> syntax and grab title

### ISSUE THREAD

**Issue by trailjeep** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#16]
Thank you for this great plugin.

It would be nice if it could override `<file>` as well as `<code>`.

Also if it could parse the dokuwiki code and file syntax titles that would be awesome, as I wouldn't have to rewrite anything.

Reference: [Downloadable Code Blocks](https://www.dokuwiki.org/wiki:syntax#downloadable_code_blocks)
`<code bash TITLE></code>`
`<file bash TITLE></file>`

**Comment by crazy-max** [comment]
Hi @trailjeep,

Yes it's definitely possible. Like `<code>` tag i will add a new option to override `<file>` tag.
And thanks for your support ;)

**Comment by crazy-max** [comment]
@trailjeep Available in the latest release (20180301). Override option display a list of tags to override now and you can add some more in the settings.
