### ISSUE TITLE
please add brush for go lang 

### ISSUE THREAD

**Issue by hongsoog** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#17]
Thanks for your work on syntaxhighlighter4.

Though c++ brush can temporarily highlight go syntax, 
It would be happy to have complete go lang brush.

Cheers.

**Comment by crazy-max** [comment]
@hongsoog, I do not develop brushes for syntaxhighlighter. I suggest you open an issue on the [official repository](https://github.com/syntaxhighlighter/syntaxhighlighter/issues) for this or develop yourself the brush if you want me to integrate it. Thanks
