### ISSUE TITLE
Cannot add code to dokuwiki page

### ISSUE THREAD

**Issue by Blommeke77** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#18]
Hello,

When I try to save some bash code to a dokuwiki page, I get an error on this specific line:

_spawn sed -i "/$host/d" /root/.ssh/known_hosts_

Is there a way to bypass this?

Kind regards,

John

**Comment by crazy-max** [comment]
Hi @Blommeke77, i cannot reproduce your issue :

![image](https://user-images.githubusercontent.com/1951866/39990612-48329f46-576d-11e8-865e-28522152b9e8.png)

Can you post your wiki code?

**Comment by Blommeke77** [comment]
Hi Crazy-Max,

Thanks for your quick response. Below the complete code. 
When I try to save or preview this page I get the following error:

_You don't have permission to access /doku.php on this server._ 

`<sxh bash>
#!/usr/bin/expect

## SSH host login settings
set host "xxx.xxx.xxx.xxx"
set port "4118"
set user "username"
set pass "password"

## Encryption key between 8-15 characters
set encryptionkey "********"

## Script variables
set multiprompt "(%|#|>|\\$ )"
set prompt [string trim $multiprompt]
set timeout 30
set counter 0
set date [exec date +%F-%H-%M-%S]

## Check if host is alive and responds to PING
## -c number of pings to perform
## -i interval
## -W timeout
spawn ping -c 2 -i 3 -W 1 $host

expect {
	" 0%" {
	## Host is alive
		## Remove SSH host from known_hosts file
		spawn sed -i "/$host/d" /root/.ssh/known_hosts
		expect -re $prompt
		## Login to SSH host and accept SSH fingerprint
		spawn ssh $user@$host -p $port
		expect "Are you sure you want to continue connecting (yes/no)?"
		send "yes\r"
		expect "Password:"
		send "$pass\r"
		expect -re $prompt

		## Send commands to SSH host
		send "backup image ${encryptionkey} to usb BUP-${date}.fxi\r"
		expect {
			timeout {
			   incr counter;
			   if { $counter == 15 } {
				   puts "Backup took longer than 5 minutes.\r\r";
				   exit 1;
				}
				puts "Waiting for backup to complete...\r\r";
				exp_continue;
			}
			-re $prompt {
				puts "Backup is complete.\r\r";
			}
		}
		## Delete existing auto-restore backup file
		send "no usb auto-restore\r"
		expect -re $prompt

		## Convert backup file to auto-restore backup file
		send "usb auto-restore ${encryptionkey} BUP-${date}.fxi\r"
		expect {
			timeout {
			   incr counter;
			   if { $counter == 15 } {
				   puts "Creating auto-restore backup took longer than 5 minutes.\r\r";
				   exit 1;
				}
				puts "Waiting for creating auto-restore backup to complete...\r\r";
				exp_continue;
			}
			-re $prompt {
				puts "Creating auto-restore backup is complete.\r\r";
				}
			}
		}
	" 100%" {
	## Host not alive
	puts "Cannot connect to host."
	}
}
## Exit SSH session
send "exit\r\r"
</sxh>`

**Comment by crazy-max** [comment]
Unfortunately I still don't reproduce your problem :

![sxh-bash](https://user-images.githubusercontent.com/1951866/39993651-dc12695e-5776-11e8-8289-60f33c657131.png)

Can you try on a new DokuWiki installation? Did you also check if another plugin was in conflict?

**Comment by Blommeke77** [comment]
Hi CrazyMax,

 

Thanks again. I installed Dokuwiki on another system and no wit works just fine with all the same plug-ins.

Must be something on my hosting VPS.

 

Keep up the good work! Love this plug-in. 😉

 

Kind regards,

 

John

 

Van: CrazyMax [mailto:notifications@github.com] 
Verzonden: maandag 14 mei 2018 13:01
Aan: crazy-max/dokuwiki-plugin-syntaxhighlighter4 <dokuwiki-plugin-syntaxhighlighter4@noreply.github.com>
CC: Blommeke77 <jcblom@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [crazy-max/dokuwiki-plugin-syntaxhighlighter4] Cannot add code to dokuwiki page (#18)

 

Unfortunately I still don't reproduce your problem :

 <https://user-images.githubusercontent.com/1951866/39993651-dc12695e-5776-11e8-8289-60f33c657131.png> 

Can you try on a new DokuWiki installation? Did you also check if another plugin was in conflict?
