### ISSUE TITLE
Enable highlighting of sections within a line

### ISSUE THREAD

**Issue by Haratsu** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#20]
It would be create to have a chance to only highlight a section of a line e.g. column 20 to 30. This is useful to clearly indicate portions of a code to alter. For example using current highlight option the following extension to the syntax shall work:
 * current behaviour: `highlight: [10, 20-30]` <- to highlight complete lines
 * additional behaviour: `highlight: [10:5-10, 20-30:13-17]` <- to highlight column 5 to ten in line 10 and column 13 to 17 in each line from 20 to 30 (like a block 'select')

**Comment by crazy-max** [comment]
@Haratsu Not possible at this time with SyntaxHighlighter. I suggest you [open an issue on the official repository](https://github.com/syntaxhighlighter/syntaxhighlighter/issues) for this. Thanks.
