### ISSUE TITLE
[Request] Clipboard button

### ISSUE THREAD

**Issue by codingtub** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#22]
A simple button to copy all the source code to clipboard (like clipboard.js provides)

![image](https://user-images.githubusercontent.com/20973893/44043485-43bf4a1a-9f23-11e8-819f-965f0c67ade2.png)

**Comment by crazy-max** [comment]
This is an upstream issue for syntaxhighlighter, not this plugin. But as stated on syntaxhighlighter repository :

"Well, it's finally happening -- no more Flash. I think I've came up with user interface to copy code to clipboard which is a lot more intuitive and almost too easy.
If you double click anywhere on the code, the entire code view is replaces with a pre-selected view from which users can copy with a simple Ctrl/Cmd-C. Clicking anywhere else returns the view to the original state."

See [this comment](https://github.com/syntaxhighlighter/syntaxhighlighter/issues/65#issuecomment-2959294) for more info.

Open an issue on [syntaxhighlighter repo](https://github.com/syntaxhighlighter/syntaxhighlighter) if you want this feature.

**Comment by codingtub** [comment]
Oh ok, I somehow oversaw that I opened the issue for the wrong repo, sorry about that 😅
