### ISSUE TITLE
Underscores in last line get cut off

### ISSUE THREAD

**Issue by hkockerbeck** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#23]
When the last line contains underscores, they get cut off. For example,

`my_item.do_something_with_it(5);`

looks like

`my item.do something with it(5);`

It looks like the line height is just that little bit too small. The problem doesn't appear in any lines above the last, though. I've tested it on Firefox and Chromium (both using Bitstream Vera Sans Mono as font).

**Comment by crazy-max** [comment]
This issue is linked to syntaxhighlighter/syntaxhighlighter#406, I will add the [CSS hack](https://github.com/syntaxhighlighter/syntaxhighlighter/issues/406#issuecomment-374555891) on the next release.

**Comment by crazy-max** [comment]
Solved in latest release
