### ISSUE TITLE
Gutter option doesn't seem to be working

### ISSUE THREAD

**Issue by leveled** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#3]
An example like follows: 
`<sxh bash; gutter: off; title: Ping scan 10.11.0.1 subnet> nmap -sn 10.11.0.1/24</sxh>`

Is rendering a block with numbers on

**Comment by crazy-max** [comment]
The values are `true` or `false`
I will edit the README.md

**Comment by crazy-max** [comment]
Linked to [DokuWiki Issue #1549](https://github.com/splitbrain/dokuwiki/pull/1549)
