### ISSUE TITLE
Option to use <code/> instead of <sxh/>

### ISSUE THREAD

**Issue by mlinchitstest** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#4]
Could you add an option to  override the default Geshi highlighter? Another addon (Code Prettifier) does this, and it helps because you can get the syntax highlighted in the actual code mirror  (of course it will still only highlight what Geshi supports—but at least most languages will be highlighted). It would also make it easier to switch between Geshi and your addon if technical difficulties emerge with either.

thanks

**Comment by crazy-max** [comment]
Hi,

Ok stay tuned ;)

**Comment by crazy-max** [comment]
Solved in the latest release
