### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by sv-dev** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#6]
Hello!

After installing I have next errors

Warning: Declaration of syntax_plugin_syntaxhighlighter4::handle($match, $state, $pos, Doku_Handler &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\syntaxhighlighter4\syntax.php on line 199

Warning: Declaration of syntax_plugin_syntaxhighlighter4::render($mode, Doku_Renderer &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\syntaxhighlighter4\syntax.php on line 199

Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\dokuwiki\lib\plugins\syntaxhighlighter4\syntax.php:199) in C:\xampp\htdocs\dokuwiki\inc\actions.php on line 210

Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\dokuwiki\lib\plugins\syntaxhighlighter4\syntax.php:199) in C:\xampp\htdocs\dokuwiki\lib\tpl\dokuwiki\main.php on line 12

I think I because PHP7. 
Can you fix it please.

**Comment by sv-dev** [comment]
https://github.com/dokufreaks/plugin-tag/issues/154
here the same problem

I just found solution here
https://github.com/cosmocode/dokuwiki-plugin-note/issues/1

So, the question is. If I do the same, is it will be ok?

**Comment by crazy-max** [comment]
Yes it is.
I will make a new release asap

**Comment by crazy-max** [comment]
Fix in the latest release 20161128

**Comment by sv-dev** [comment]
thank you, thank you, thank you )

понедельник, 28 ноября 2016 г. пользователь Cr@zy написал:

**Comment by sv-dev** [comment]
Hello!

Unfortunately, when I go to admin page
/doku.php?id=user:admin&do=admin
There are 2 mistakes ((

Warning: Declaration of syntax_plugin_catlist::handle($match, $state, $pos,
&$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match,
$state, $pos, Doku_Handler $handler) in
C:\xampp\htdocs\dokuwiki\lib\plugins\catlist\syntax.php on line 334



 Warning: Declaration of syntax_plugin_catlist::render($mode, &$renderer,
$data) should be compatible with DokuWiki_Syntax_Plugin::render($format,
Doku_Renderer $renderer, $data) in
C:\xampp\htdocs\dokuwiki\lib\plugins\catlist\syntax.php on line 334


2016-11-28 2:15 GMT+02:00 gertin 7 <gertin7@gmail.com>:

**Comment by sv-dev** [comment]
Hello!

Unfortunately, when I go to admin page
/doku.php?id=user:admin&do=admin
There are 2 mistakes ((

Warning: Declaration of syntax_plugin_catlist::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\catlist\syntax.php on line 334



 Warning: Declaration of syntax_plugin_catlist::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\catlist\syntax.php on line 334

**Comment by sv-dev** [comment]
I left it here

https://github.com/crazy-max/dokuwiki-plugin-syntaxhighlighter4/issues/9

2016-11-29 11:07 GMT+02:00 gertin 7 <gertin7@gmail.com>:
