### ISSUE TITLE
Fresh dokuwiki install and add plugin syntashighlighter4 gives error

### ISSUE THREAD

**Issue by ferpega** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#8]
Hello,

after a fresh  install of dokuwiki and _only_ this plugin installed, now I have this error trying to access my wiki:

Parse error:  syntax error, unexpected '[' in <path>/lib/plugins/syntaxhighlighter4/action.php on line 41

I have PHP Version 5.3.27

**Comment by crazy-max** [comment]
Hi, it's link to the [Short syntax for arrays](https://wiki.php.net/rfc/shortsyntaxforarrays) introduced in PHP 5.4.
I will make a new release to resolve this issue.

**Comment by crazy-max** [comment]
Available in tha latests release 20161128

**Comment by ferpega** [comment]
Thanks.
