### ISSUE TITLE
Error in admin page (PHP 7 error)

### ISSUE THREAD

**Issue by sv-dev** [crazy-max/dokuwiki-plugin-syntaxhighlighter4#9]
Hello!

Unfortunately, when I go to admin page
/doku.php?id=user:admin&do=admin
There are 2 mistakes ((

Warning: Declaration of syntax_plugin_catlist::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\catlist\syntax.php on line 334

 Warning: Declaration of syntax_plugin_catlist::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\catlist\syntax.php on line 334

**Comment by crazy-max** [comment]
Hi,

If you read the errorstack, the plugin `catlist` is involved not mine this time ;)

**Comment by sv-dev** [comment]
yes, I understand later )
sorry )

вторник, 29 ноября 2016 г. пользователь Cr@zy написал:

**Comment by sv-dev** [comment]
I understood )

вторник, 29 ноября 2016 г. пользователь Cr@zy написал:
